import { Inter } from "next/font/google";
import stule from "@/app/pages/react_1/styles.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
      <div className={stule.users_1}>{children}</div>
    
  );
}
